# Generated by Django 4.1.7 on 2023-04-01 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_user_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='orders',
            name='ctg',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.BigIntegerField(),
        ),
    ]
