# Generated by Django 4.1.7 on 2023-04-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_rename_user_orders_user_id_orders_ctg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='company_name',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='name',
            field=models.CharField(default=1, max_length=56),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='phone_number',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='product',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='orders',
            name='user_id',
            field=models.BigIntegerField(),
        ),
    ]
