# Generated by Django 4.1.7 on 2023-04-01 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_orders_company_name_orders_name_orders_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='updated_at',
        ),
    ]
