# Generated by Django 4.1.7 on 2023-04-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_user_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='log',
        ),
        migrations.AlterField(
            model_name='user',
            name='company_name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=56, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
