# Generated by Django 4.1.7 on 2023-04-03 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_user_id_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ctg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.category'),
        ),
    ]
