# Generated by Django 4.1.7 on 2023-04-03 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_subcategory_product_sub_ctg'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='ctg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.category'),
        ),
    ]
