# Generated by Django 4.1.7 on 2023-04-13 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_subcategory_ctg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='code',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.RemoveField(
            model_name='user',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
