# Generated by Django 4.1.7 on 2023-04-13 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_remove_orders_name_remove_product_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
