# Generated by Django 4.1.7 on 2023-04-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_user_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='company_name',
        ),
        migrations.AddField(
            model_name='orders',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
