# Generated by Django 4.1.7 on 2023-04-16 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sub_ctg',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
