# Generated by Django 4.1.7 on 2023-04-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_product_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='log',
            field=models.JSONField(verbose_name={'order': []}),
        ),
    ]
