# Generated by Django 4.1.7 on 2023-04-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_alter_product_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='log',
        ),
        migrations.AddField(
            model_name='user',
            name='log',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
