# Generated by Django 4.1.7 on 2023-04-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_remove_product_log_user_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='log',
            field=models.JSONField(verbose_name={'order': []}),
        ),
    ]
