# Generated by Django 4.1.7 on 2023-04-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_alter_user_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='log',
            field=models.JSONField(default=1, verbose_name={'order': 0}),
            preserve_default=False,
        ),
    ]
