# Generated by Django 4.1.7 on 2023-04-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0030_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
