# Generated by Django 4.1.7 on 2023-04-21 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0031_alter_messages_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='ctg',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='image',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='orders',
            name='product',
            field=models.TextField(),
        ),
    ]
